# Generated by Django 5.2.3 on 2025-07-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('blood_type', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=100)),
                ('quantity_needed', models.PositiveIntegerField(help_text='Quantity needed in mL')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('blood_type', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=100)),
                ('quantity_donated', models.PositiveIntegerField(help_text='Quantity donated in mL')),
            ],
        ),
    ]
