# Generated by Django 5.2.3 on 2025-07-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
    ]
