# Generated by Django 5.2.3 on 2025-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_remove_donor_donated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='donated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
