# Generated by Django 5.2.4 on 2025-07-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0012_donor_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
    ]
