# Generated by Django 5.2.3 on 2025-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_bloodrequest_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('blood_type', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=100)),
                ('quantity_received', models.PositiveIntegerField(help_text='Quantity in mL')),
                ('contact', models.CharField(default='', max_length=15)),
                ('received_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
