# Generated by Django 5.2.3 on 2025-07-03 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_bloodreceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donated_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
