# Generated by Django 5.2.3 on 2025-07-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_donor_donated_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodReceived',
        ),
        migrations.AlterField(
            model_name='donor',
            name='donated_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
