# Generated by Django 5.2.3 on 2025-07-03 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_bloodrequest_requested_date_donor_donated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='requested_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donor',
            name='donated_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
