# Generated by Django 5.2.4 on 2025-07-24 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_bloodrequest_user_donor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='donated_date',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='quantity_donated',
        ),
        migrations.AddField(
            model_name='donor',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='donation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donor',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='units_donated',
            field=models.PositiveIntegerField(default=1, help_text='Units donated (1 unit ≈ 450 mL)'),
        ),
    ]
