# Generated by Django 5.2.4 on 2025-07-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0011_remove_donor_age_remove_donor_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
