# Generated by Django 5.2.4 on 2025-07-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0013_bloodrequest_verified_alter_bloodrequest_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
