"""
Django settings for BBMS project.

Generated by 'django-admin startproject' using Django 5.2.3.

Docs:
- Settings overview: https://docs.djangoproject.com/en/5.2/topics/settings/
- Full reference: https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# 📁 Base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------------
# 🔐 Security Settings
# -------------------------------
SECRET_KEY = 'django-insecure-$@6ozw19qn7u!#cd2qzbbyraqu357@sjy#lm+jh91l6(nt542@'
# ❗ Replace with environment variable in production

DEBUG = True  # ❗ Set to False in production to disable detailed error pages

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'your-render-url.onrender.com',  # ✅ Add Render domain here
]

# -------------------------------
# 📦 Installed Apps
# -------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',            # Admin interface
    'django.contrib.auth',             # Authentication system
    'django.contrib.contenttypes',     # Content type framework
    'django.contrib.sessions',         # Session management
    'django.contrib.messages',         # Messaging framework
    'django.contrib.staticfiles',      # Static file handling

    'blood',                # ✅ Core app for donations and requests
    'axes',                 # ✅ Login rate-limiting and lockout
    'accounts',             # ✅ User registration and profile
    'captcha',              # ✅ Captcha protection for signup
    'widget_tweaks',        # ✅ Template form customization
]


# -------------------------------
# ⚙️ Middleware
# -------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # ✅ Serve static files efficiently in production
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',

    'axes.middleware.AxesMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# -------------------------------
# 🔐 Authentication Backends
# -------------------------------
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',              # ✅ Enables Axes login tracking
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth
]


# -------------------------------
# 🔗 URL & Templates
# -------------------------------
ROOT_URLCONF = 'BBMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # ✅ Global templates folder
        'APP_DIRS': True,                  # ✅ Enables app-level templates
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # Required for login forms
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BBMS.wsgi.application'


# -------------------------------
# 🗃️ Database
# -------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # ✅ Simple local DB
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# ❗ For Render, switch to PostgreSQL and use DATABASE_URL env var


# -------------------------------
# 🔐 Password Validators
# -------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# -------------------------------
# 🌍 Internationalization
# -------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# -------------------------------
# 🎨 Static Files
# -------------------------------
STATIC_URL = '/static/'  # ✅ URL prefix for static files

# ✅ Directory where collectstatic will gather static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Optional: enable gzip compression and caching
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# -------------------------------
# 🔑 Default Primary Key
# -------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# -------------------------------
# 🔐 Session & Login Behavior
# -------------------------------
LOGIN_URL = 'login'  # ✅ Redirects unauthenticated users to login
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # ✅ Ends session when browser closes
LOGIN_REDIRECT_URL = '/accounts/dashboard/'  # ✅ Post-login landing page


# -------------------------------
# 🛡️ Django Axes Configuration
# -------------------------------
AXES_FAILURE_LIMIT = 5           # ✅ Max failed login attempts before lockout
AXES_COOLOFF_TIME = 1            # ✅ Lockout duration in hours
AXES_LOCKOUT_CALLABLE = 'blood.views.custom_lockout_response'  # ✅ Custom lockout handler
AXES_ENABLED = True              # ✅ Toggle Axes protection
